RATING_DATE = 'rating_date'
ANALYSTS_MIN_MEAN_SUCCESS_RATE = 'ANALYSTS_MIN_MEAN_SUCCESS_RATE'
DAYS_SINCE_ANALYSTS_ALERT = 'DAYS_SINCE_ANALYSTS_ALERT'
QUESTIONABLE_SOURCES = []

EMISSIONS = 'emissions'
